/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as XmlsRouteImport } from './routes/xmls'
import { Route as FechamentosRouteImport } from './routes/fechamentos'
import { Route as EmpresasRouteImport } from './routes/empresas'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FechamentosFechamentoIdRouteImport } from './routes/fechamentos_.$fechamentoId'

const XmlsRoute = XmlsRouteImport.update({
  id: '/xmls',
  path: '/xmls',
  getParentRoute: () => rootRouteImport,
} as any)
const FechamentosRoute = FechamentosRouteImport.update({
  id: '/fechamentos',
  path: '/fechamentos',
  getParentRoute: () => rootRouteImport,
} as any)
const EmpresasRoute = EmpresasRouteImport.update({
  id: '/empresas',
  path: '/empresas',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FechamentosFechamentoIdRoute = FechamentosFechamentoIdRouteImport.update({
  id: '/fechamentos_/$fechamentoId',
  path: '/fechamentos/$fechamentoId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/empresas': typeof EmpresasRoute
  '/fechamentos': typeof FechamentosRoute
  '/xmls': typeof XmlsRoute
  '/fechamentos/$fechamentoId': typeof FechamentosFechamentoIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/empresas': typeof EmpresasRoute
  '/fechamentos': typeof FechamentosRoute
  '/xmls': typeof XmlsRoute
  '/fechamentos/$fechamentoId': typeof FechamentosFechamentoIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/empresas': typeof EmpresasRoute
  '/fechamentos': typeof FechamentosRoute
  '/xmls': typeof XmlsRoute
  '/fechamentos_/$fechamentoId': typeof FechamentosFechamentoIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/empresas'
    | '/fechamentos'
    | '/xmls'
    | '/fechamentos/$fechamentoId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/empresas'
    | '/fechamentos'
    | '/xmls'
    | '/fechamentos/$fechamentoId'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/empresas'
    | '/fechamentos'
    | '/xmls'
    | '/fechamentos_/$fechamentoId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  EmpresasRoute: typeof EmpresasRoute
  FechamentosRoute: typeof FechamentosRoute
  XmlsRoute: typeof XmlsRoute
  FechamentosFechamentoIdRoute: typeof FechamentosFechamentoIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/xmls': {
      id: '/xmls'
      path: '/xmls'
      fullPath: '/xmls'
      preLoaderRoute: typeof XmlsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fechamentos': {
      id: '/fechamentos'
      path: '/fechamentos'
      fullPath: '/fechamentos'
      preLoaderRoute: typeof FechamentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/empresas': {
      id: '/empresas'
      path: '/empresas'
      fullPath: '/empresas'
      preLoaderRoute: typeof EmpresasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fechamentos_/$fechamentoId': {
      id: '/fechamentos_/$fechamentoId'
      path: '/fechamentos/$fechamentoId'
      fullPath: '/fechamentos/$fechamentoId'
      preLoaderRoute: typeof FechamentosFechamentoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  EmpresasRoute: EmpresasRoute,
  FechamentosRoute: FechamentosRoute,
  XmlsRoute: XmlsRoute,
  FechamentosFechamentoIdRoute: FechamentosFechamentoIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
